config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :cars do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
    collection do
      get 'my_cars', to: 'cars#my_cars'
    end
  end
  get 'cars/image/:id', to: 'cars#image', as: 'car_image'
  patch 'cars/image/:id', to: 'cars#image_update'
  get 'cars/description/:id', to: 'cars#description', as: 'car_description'
  patch 'cars/description/:id', to: 'cars#description_update'
  get 'search', to: 'search#search'
  
  namespace :admin do
    resources :cars
    resources :users do
      member do
        get :toggle_status
      end
    end
  end
  root "cars#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord

  VENDOR_NAMES = ['Toyota', 'Honda', 'Suzuki', 'Tesla', 'Mercedes', 'BMW', 'Hyundai', 'Kia'].freeze
  validates :vendor, :car_name, :model, :engine_capacity, :millage, :color, :price, presence: true

  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many_attached :images

  accepts_nested_attributes_for :comments

  def self.search(params)
    results = all
    results = results.where("vendor LIKE ?", "%#{params[:vendor]}%") if params[:vendor].present?
    results = results.where("car_name LIKE ?", "%#{params[:car_name]}%") if params[:car_name].present?
    results = results.where("model LIKE ?", "%#{params[:model]}%") if params[:model].present?
    results = results.where("category LIKE ?", "%#{params[:category]}%") if params[:category].present?
    results = results.where("engine_capacity LIKE ?", "%#{params[:engine_capacity]}%") if params[:engine_capacity].present?
    results
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :car
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/user.rb
class User < ApplicationRecord
  enum role: { user: 'user', admin: 'admin' }
  enum status: { active: 'active', inactive: 'inactive' }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :cars, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :comments
end

app/controllers/admin/cars_controller.rb
class Admin::CarsController < AdminController
  before_action :set_admin_car, only: [:destroy , :show]

  def index
    @cars = Car.all
  end

  def show; end

  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to admin_car_path, notice: "Car was deleted sucessfully" }
    end
  end

  private

  def set_admin_car
    @car = Car.find(params[:id])
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_admin_user, only: [:show, :toggle_status, :destroy]

  def index
    @users = User.all
  end

  def show
    @cars = @user.cars.all
  end

  def toggle_status
    @user.status = @user.active? ? 'inactive' : 'active'
    if @user.save
      redirect_to admin_users_path(@user), notice: 'User status has been updated.'
    else
      redirect_to admin_users_path(@user), alert: 'Failed to update user status.'
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_path(@users), notice: "User was deleted sucessfully" }
    end
  end

  private

  def set_admin_user
    @user = User.find(params[:id])
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception, prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:first_name, :last_name, :email, :password, :states, :cities) }
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :states, :cities) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password) }
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_cars, only: [:edit, :show, :update,  :destroy, :image, :image_update, :description, :description_update]

  def index
    @cars = Car.paginate(page: params[:page], per_page: 4).order(created_at: :desc)
  end

  def my_cars
    @user_cars = current_user.cars
    if @user_cars.blank?
      flash.now[:alert] = "You have not added any cars yet."
    end
  end

  def show
    @comment = current_user.comments.build
  end

  def new
    @car = Car.new
  end

  def edit; end

  def create
    @car = Car.new(car_params)
    @car.user_id = current_user.id
    respond_to do |format|
      if @car.save
        session[:car_id] = @car.id
        format.html { redirect_to car_image_path(@car) }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html {redirect_to car_image_path }
      else
        format.html (render :edit )
      end
    end
  end

  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_path, notice: "Car was deleted sucessfully" }
    end
  end

  def image; end

  def image_update
    respond_to do |format|
      if @car.update (car_params)
        format.html {redirect_to car_description_path}
      else
        format.html (render :image)
      end
    end
  end

  def description; end

  def description_update
    respond_to do |format|
      if @car.update (car_params)
        format.html {redirect_to cars_path}
      else
        format.html (render :description)
      end
    end
  end

  private

  def set_cars
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:vendor, :car_name, :model, :engine_capacity, :millage, :category, :color, :price, :description, :user_id, images:[], comments_attributes: [:content])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.car_id = params[:car_id]
    @comment.save
    redirect_to car_path(params[:car_id])
  end

private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :car_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_car, only: [:create, :destroy]

  def create
    @like = current_user.likes.build(car: @car)
    if @like.save
      respond_to do |format|
        format.html{redirect_to car_path(@car)}
        format.js
      end
    end
  end

  def destroy
    @like = current_user.likes.find(params[:id])
    @like.destroy
    respond_to do |format|
    format.html{redirect_to car_path(@car)}
    format.js
    end
  end

  private

  def find_car
    @car = Car.find(params[:car_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home; end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @results = Car.search(params)
    respond_to do |format|
      format.html { render partial: 'cars/cars', locals: { cars: @results } }
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true
class Users::SessionsController < Devise::SessionsController
  def create
    user = User.find_by(email: params[:user][:email])
    if user.present? && user.inactive?
      flash[:alert] = "Your account is inactive. Please contact to admin."
      redirect_to new_user_session_path
    else
      super 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/admin/cars/index.html.erb
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Vendor</th>
        <th scope="col">Car_name</th>
        <th scope="col">Model</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @cars.each do |car| %>
        <tr>
          <td><%= car.vendor %></td>
          <td><%= car.car_name%></td>
          <td><%= car.model %></td>
          <td><%= link_to "Show More", admin_car_path(car), class: "btn btn-secondary" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/cars/show.html.erb
<p style="color: green"><%= notice %></p>
<p id="notice"><%= notice %></p>
<div class="container show">
  <div class="row">
    <h1 class="details"> Details About Car </h1>
    <div class="col-md-7 ">
      <% @car.images.each do |image| %>
        <%= image_tag image, class: 'show-images'%>
      <% end %>
    </div>
    <div class="col-md-5 show-details">
      <div class="jumbotron">
        <h1 class="display-4"> 
          <%= @car.vendor %>
          <%= @car.car_name %>
        </h1>
        <p class="lead">
          <%= @car.model %> |
          <%= @car.engine_capacity%> |
          <%= @car.millage%>
        </p>
        <p class="lead">
          <%= @car.category %> |
          <%= @car.color %> |
          <%= @car.price %>
        </p>
        <h1> Description: </h1>
        <h3><%= @car.description %></h3>
        <br>
        <p><%= @car.likes.count %> <%= (@car.likes.count) == 1 ? 'Like' : 'Likes'%></p>
        <hr class="my-4">
        <%= link_to 'Edit', edit_admin_car_path, class: "btn btn-secondary" %>  
        <%= link_to 'Back to Cars', admin_cars_path, class: "btn btn-secondary"%>
        <%= button_to admin_car_path, method: :delete, class: "btn btn-danger" do%>
          <i class="fa-solid fa-trash"></i>Delete
        <% end %>
    </div>
  </div>
</div>
<br>
<div class="container">
  <h2>Comments:</h2>
    <% @car.comments.each do |comment| %>
    <div>
      <p>
        <h3><%= comment.user.first_name %></h3> 
        <%= comment.content %>
      </p>
    </div>
    <% end %>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Status</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
        <td><%= user.first_name%></td>
        <td><%= user.email%></td>
        <td><%= link_to user.status, toggle_status_admin_user_path(user), class: "btn btn-dark" %></td>
        <td><%= link_to 'Show', admin_user_path(user), class: "btn btn-secondary" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="display-4"> 
      <%= @user.first_name %>
      <%= @user.last_name %>
    </h1>
    <p class="lead">
      <%= @user.email %> |
      <%= @user.role %> |
      <%= @user.status%>
    </p>
    <p class="lead">
      <%= @user.states%>
      <%=@user.cities%>
    </p>
    <br>
    <hr class="my-4">
    <%= link_to "Back to users", admin_users_path, class:"btn btn-secondary" %>
    <%= button_to admin_user_path(@user), method: :delete, class: "btn btn-danger" do %>
      <i class="fa-solid fa-trash"></i>Delete
    <% end %>
  </div>
  <hr>
</div>
<div class="container">
  <h1> User Cars: </h1>
  <%= render 'shared/cars', locals: { cars: @cars } %>
</div>

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <p>
    <strong>Vendor:</strong>
    <%= car.vendor %>
  </p>

  <p>
    <strong>Car_Name:</strong>
    <%= car.car_name %>
  </p>

  <p>
    <strong>Model:</strong>
    <%= car.model %>
  </p>

  <p>
    <strong>Engine_Capacity:</strong>
    <%= car.engine_capacity %>
  </p>

  <p>
    <strong>Millage:</strong>
    <%= car.millage %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= car.category %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= car.color %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= car.price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= car.description %>
  </p>

</div>

app/views/cars/_comments.html.erb
<%= form_with(model: [@car, @comment]) do |f| %>
  <div class="form-group">
    <%= f.label :content, 'New comment' %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <br>
  <%= f.submit 'Submit', class: 'btn btn-secondary' %>
<% end %>

app/views/cars/_form.html.erb
<%= form_for(@car, url: cars_path) do |f| %>
  <h1> Add Details </h1>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :vendor, style: "display: block; "  %>
        <%= f.select :vendor, options_for_select(Car::VENDOR_NAMES), { }, class: 'form-control select-custom', include_blank: true, required: true %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :car_name, style: "display: block" %>
        <%= f.text_field :car_name, class: "form-control", required: true %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :model, style: "display: block" %>
        <%= f.text_field :model, class: "form-control", required: true %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :engine_Capacity, style: "display: block" %>
        <%= f.text_field :engine_capacity, class: "form-control", required: true %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :millage, style: "display: block" %>
        <%= f.text_field :millage, class: "form-control", required: true %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :category, style: "display: block" %>
        <%= f.text_field :category, class: "form-control", required: true %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :color, style: "display: block" %>
        <%= f.text_field :color, class: "form-control", required: true %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :price, style: "display: block" %>
        <%= f.text_field :price, class: "form-control", required: true %>
      </div>
    </div>
  </div>

    <br>
    <div class="form-group">
      <%= f.submit 'Next Step', class: "btn btn-secondary" %>  
    </div>
    <br>
  </div>
<% end %>

app/views/cars/_like.html.erb
<div class="like">
  <% pre_like = @car.likes.find { |like| like.user_id == current_user.id} %>
  <% if pre_like %>
    <%= button_to car_like_path(@car, pre_like), method: :delete, remote: true, data: { turbo: false }  do %>
      <i class="fa fa-thumbs-down" aria-hidden="true"></i>
    <% end %>
  <% else %>
    <%= button_to car_likes_path(@car), method: :post, remote: true, data: { turbo: false }  do %>
      <i class="fa fa-thumbs-up" aria-hidden="true"></i>
    <% end %>
  <% end %>
</div>
<p><%= @car.likes.count %> <%= (@car.likes.count) == 1 ? 'Like' : 'Likes'%></p>

app/views/cars/_search.html.erb
<div class="search-classified-bg">
  <div class="search-classified-text text-center generic-white">
    <div class="style">
      <h1>Find Used Cars in Pakistan</h1>
      <p>With thousands of cars, we have just the right one for you</p>
    </div>
    <div class="search-classified" >
      <div class= "btn-classified-container text-center">
        <%= form_with url: search_path, method: :get do |f| %>
          <%= f.text_field :vendor, placeholder: "Vendor", class: 'search-fields' %>
          <%= f.text_field :car_name, placeholder: "Car_Name", class: 'search-fields'%>
          <%= f.text_field :model, placeholder: "Model", class: 'search-fields' %>
          <%= f.text_field :engine_capacity, placeholder: "Engine_Capacity", class: 'search-fields'%> 
          <%= button_tag type: 'submit', class: "btn btn-info", id: "search-button" do %>
            <i class="fa-brands fa-searchengin"></i> Search
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cars/description.html.erb
<div class="container" >
  <h1> Add a Car </h1>
  <br>
  <%= form_for(@car, url: car_description_path(@car)) do |f| %>
    <h2> Description </h2>
    <div class="form-group">
      <%= f.text_area :description, rows: 10, coloumns: 10, class: "form-control", required: true%>
    </div>
    <br>
    <%= f.submit 'Create Car', class: "btn btn-secondary" %>
  <% end %>
  <br>
</div>

app/views/cars/edit.html.erb
<h3> Edit this car <h3>

<%= render "form" %>

app/views/cars/image.html.erb
<div class="container">
  <h1> Add a Car </h1>
  <br>
    <%= form_for(@car, url: car_image_path(@car)) do |f| %>
      <h2> Images </h2>
      <div class="form-group">
        <%= f.file_field :images, :multiple => true, class: "form-control"%>
      </div>
    </i>
    <br>
      <%= f.submit 'Next Step', class: "btn btn-secondary"%>
  <% end %>
  <br>
</div>

app/views/cars/index.html.erb
<%= render 'shared/car-carousel'%>
<div id="cars">
  <%= render partial: "shared/cars", locals: { cars: @cars } %>
</div>
<div class="center-pagination">
  <div class="pagination">
    <%= will_paginate @car %>
  </div>
</div>

app/views/cars/my_cars.html.erb
<div class="row">
  <% if @user_cars.present? %>
    <% @user_cars.each do |car| %>
      <div class="card">
        <div class="image">
          <% if car.images.present? %>
            <%= image_tag car.images.first, style: "width: 100%; height: 400px;" %>
          <% end %>
        </div>
        <div class="text-align">
          <div class="card-body">
            <h5 class="card-title"><%= car.car_name %> </h5>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= car.vendor %></li>
            <li class="list-group-item"><%= car.car_name %></li>
            <li class="list-group-item"><%= car.model %></li>
          </ul>
          <div class="card-body">
            <h6 class="card-text"><%= car.description %></h6>
            <a class="card-link"><%= link_to "Show More", car_path(car), class: "btn btn-secondary" %></a>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<br>

app/views/cars/new.html.erb
<div class="container">
 <%= render 'form' %>
</div>

app/views/cars/show.html.erb
<p style="color: green"><%= notice %></p>
<p id="notice"><%= notice %></p>
<div class="container show">
  <div class="row">
    <h1 class="details"> Details About Car </h1>
    <div class="col-md-7 ">
      <% @car.images.each do |image| %>
        <%= image_tag image, class: 'show-images'%>
      <% end %>
    </div>
    <div class="col-md-5 show-details">
      <div class="jumbotron">
        <h1 class="display-4"> 
          <%= @car.vendor %>
          <%= @car.car_name %>
        </h1>
        <p class="lead">
          <%= @car.model %> |
          <%= @car.engine_capacity%> |
          <%= @car.millage%>
        </p>
        <p class="lead">
          <%= @car.category %> |
          <%= @car.color %> |
          <%= @car.price %>
        </p>
        <h1> Description: </h1>
        <h3><%= @car.description %></h3>
        <br>
        <div id='likescontainer'>
          <%= render 'likes/like' %>
        </div>
        <%= render 'comments'%>
        <hr class="my-4">
        <%if @car.user_id == current_user.id %>
          <%= link_to 'Edit', edit_car_path, class: "btn btn-secondary" %>  
          <%= button_to car_path, method: :delete, class: "btn btn-danger" do %>
            <i class="fa-solid fa-trash"></i>Delete
          <% end %>
        <% end %>
        <%= link_to 'Back to Cars', cars_path, class: "btn btn-secondary"%>
    </div>
  </div>
</div>
<div class="container">
  <h2>Comments</h2>
    <% @car.comments.each do |comment| %>
    <div>
      <p>
        <h3><%= comment.user.first_name %></h3> 
        <%= comment.content %>
      </p>
    </div>
    <% end %>
</div>

app/views/comments/_comment.html.erb
<%= form_with(model: [@car, @car.comments.build]) do |f| %>
  <div class="form-group">
    <%= f.label :content, 'New comment' %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <%= f.submit 'Submit', class: 'btn btn-secondary' %>
<% end %>

app/views/comments/new.html.erb
<%= render 'comment' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JunaidWheels</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags 'application' %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <%= favicon_link_tag asset_url('admin-logo.png') %>

  <% if user_signed_in? %>
    <% if current_user.admin? %>
      <%= render "shared/admin_navigation" %>
    <% else %>
      <%= render "shared/navigation" %>
      <% if controller_name == 'cars' && action_name ==  'index' %>
        <%= render "cars/search" %>
      <% end %>
    <% end %>
  <% end %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
  <% if user_signed_in? %>
    <% if current_user.admin? %>
      <%= render "shared/admin_footer" %>
    <% else %>
      <%= render "shared/footer" %>
    <% end %>
  <% end %>
</html>

app/views/likes/_like.html.erb
<div class="like">
  <% pre_like = @car.likes.find { |like| like.user_id == current_user.id} %>
  <% if pre_like %>
    <%= button_to car_like_path(@car, pre_like), method: :delete do %>
      <i class="fa fa-thumbs-down" aria-hidden="true"></i>
    <% end %>
  <% else %>
    <%= button_to car_likes_path(@car), method: :post do %>
      <i class="fa fa-thumbs-up" aria-hidden="true"></i>
    <% end %>
  <% end %>
</div>
<p><%= @car.likes.count %> <%= (@car.likes.count) == 1 ? 'Like' : 'Likes'%></p>
 

app/views/likes/create.js.erb
$('#likescontainer').append("<%= j (render partial: 'likes/like') %>")

app/views/pages/home.html.erb
<h1> This is my Pakwheels_Clone <h1>

app/views/shared/_admin_navigation.erb
<nav class="navbar navbar-expand-lg ,bg-body-tertiary">
  <div class="container-fluid">
    <div class="admin-nav-logo">
      <a href="/admin_cars">
        <%= image_tag "admin-logo.png", class: "main-logo" %>
      </a>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ">
        <div class="bt-margin">
          <%= link_to  admin_users_path, class: "btn btn-primary"  do%>
            <i class="fa-solid fa-user"></i>User
          <% end %>
        </div>
        <%= link_to admin_cars_path, class: "btn btn-info" do %>
         <i class="fa-solid fa-car"></i>Cars
        <% end %>
        <div class="btn-margin">
          <% if user_signed_in? %>
            <%= button_to destroy_user_session_path,  method: :delete, class: "btn btn-danger" do %>
              <i class="fa-solid fa-right-from-bracket"></i>Logout
            <% end %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-secondary" %>
            <%= link_to "Sign in", new_user_session_path, class: "btn btn-secondary" %>
          <% end %>
        </div>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_car-carousel.html.erb
<div class="carousel">
  <div class="container">
    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100" src="<%= asset_path('bmw.jpg')%>" alt="First slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="<%= asset_path('elantra.jpg')%>" alt="Second slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="<%= asset_path('Aqua.jpg')%>" alt="Third slide">
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>

app/views/shared/_navigation.html.erb
<div class="nav-bar-back">
  <nav class="navbar navbar-expand-lg ,bg-body-tertiary">
    <div class="container-fluid">
      <div class="nav-logo">
        <a href="/cars">
          <%= image_tag "admin-logo.png", class: "main-logo" %>
        </a>
      </div>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ">
          <%= link_to "My Cars", my_cars_cars_path, class: "btn btn-secondary margin" %>
          <%= link_to new_car_url, class: "btn btn-secondary " do %>
            <i class="fa-solid fa-car"></i> Post an ad
          <% end %>
          <div class="btn-margin">
            <% if current_user %>
              <%= button_to destroy_user_session_path,  method: :delete, class: "btn btn-danger" do %>
                <i class="fa-solid fa-right-from-bracket"></i>Logout
              <% end %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, class: "btn btn-secondary" %>
              <%= link_to "Sign in", new_user_session_path, class: "btn btn-secondary" %>
            <% end %>
          </div>
        </ul>
      </div>
    </div>
  </nav>
</div>